### ISSUE TITLE
Round() with MidpointRoundingMode=ToPositiveInfinity produces wrong answer

### ISSUE THREAD

**Issue by michaelhkay** [Singulink/Singulink.Numerics.BigDecimal#3] opened 2021-05-28 12:20 UTC
I've picked up version 1.0.2 and MidpointRoundingMode=ToPositiveInfinity now succeeds, but it produces the wrong answer. It rounds 1.24 to 2. The midpoint rounding mode should surely only affect midpoint values.

**Comment by mikernet** [comment] 2021-05-28 12:34
That's not how directed rounding modes work. This matches intended behavior:

![image](https://user-images.githubusercontent.com/1700111/119984558-86ef7280-bf8f-11eb-92c9-6c74a4756112.png)

**Comment by mikernet** [comment] 2021-05-28 12:49
There was actually a discussion about exposing the new rounding modes on a new `DirectedRounding` enum instead but that was ultimately decided against, so the `MidPoint` part is slightly misleading. See here for example: https://github.com/dotnet/runtime/issues/27205

I'm going to close this issue as the behavior is as intended but feel free to continue the discussion here if you like :)

**Closed by mikernet** 2021-05-28 12:49 UTC

**Comment by michaelhkay** [comment] 2021-05-28 12:50
Oh dear. So the summary says "Specifies how mathematical rounding methods should process a number that is midway between two numbers." and then the detailed rules then mention that it also affects rounding of numbers that aren't midway between two numbers. Sounds like they got it badly wrong and then enshrined the bug in the documentation.

**Comment by michaelhkay** [comment] 2021-05-28 13:16
Well I guess the bottom line is that I'm still going to have to implement the desired behaviour (round midpoint towards positive infinity) myself. Any hints on the most efficient way to determine whether the value is at a midpoint? There must be a better way than rounding up and rounding down and seeing whether the absolute differences are the same.

**Comment by michaelhkay** [comment] 2021-05-28 13:22
I guess we take the absolute value, round away from zero, then restore the original signum. What a pain!

**Comment by mikernet** [comment] 2021-05-28 13:25
It's not so much that they got it wrong - they added those rounding modes to comply with IEEE required rounding modes, which they do correctly. The problem is that they named `MidPointRounding` badly in .NET 2, should have just been `RoundingMode` or similar. That opening summary of the enum is also misleading for sure - I left a comment about that in a documentation issue for the enum.

It may be worthwhile to add an overload for my rounding functions that takes an enum defined in the library with the extra rounding modes and more clearly named values.

**Comment by mikernet** [comment] 2021-05-28 13:32
If you give me a day or so I can add an overload to the rounding functions that accepts the following enum:

```cs
public enum RoundingMode
{
    MidPointToEven = 0,
    MidPointAwayFromZero = 1,
    ToZero = 2,
    ToNegativeInfinity = 3,
    ToPositiveInfinity = 4,
    
    MidPointToZero = 1000,
    MidPointToNegativeInfinity = 1001,
    MidPointToPositiveInfinity = 1002,
}
```

**Comment by mikernet** [comment] 2021-05-28 20:37
Will the above solution cover all the rounding modes you need?

**Comment by michaelhkay** [comment] 2021-05-28 21:09
Yes, I think that would meet everyone's conceivable needs!
